/**
 * Adult domain snapshot source metadata:
 * - Project: The Block List Project
 * - List: porn/adult
 * - License: Unlicense
 * - Upstream URL: https://github.com/blocklistproject/Lists/blob/master/porn.txt
 * - Snapshot generation date: 2026-02-17
 *
 * This array is intentionally maintained as a generated snapshot. Replace it with
 * a curated upstream snapshot update process; do not hand-curate entries here.
 */
export const ADULT_BLOCKLIST_SOURCE = {
  project: 'The Block List Project',
  list: 'porn',
  license: 'Unlicense',
  upstreamUrl: 'https://github.com/blocklistproject/Lists/blob/master/porn.txt',
  snapshotDate: '2026-02-17',
} as const;

export const ADULT_DOMAIN_BLOCKLIST_SNAPSHOT: readonly string[] = [
  'pornhub.com',
  'xvideos.com',
  'xnxx.com',
  'xhamster.com',
  'redtube.com',
  'youporn.com',
  'tube8.com',
  'spankbang.com',
  'eporner.com',
  'porn.com',
  'brazzers.com',
  'chaturbate.com',
  'livejasmin.com',
  'stripchat.com',
  'cam4.com',
  'myfreecams.com',
  'bongacams.com',
  'camsoda.com',
  'xnudes.com',
  'beeg.com',
  'hclips.com',
  'txxx.com',
  'sunporno.com',
  'nuvid.com',
  'tnaflix.com',
  'porntube.com',
  'thumbzilla.com',
  'drtuber.com',
  'motherless.com',
  'fapdu.com',
  'fux.com',
  'keezmovies.com',
  '3movs.com',
  'youjizz.com',
  'pornhd.com',
  'pornerbros.com',
  'slutload.com',
  'upornia.com',
  'hqporner.com',
  'sxyprn.com',
  'yespornplease.com',
  'yourporn.sexy',
  'handjobhub.com',
  'mofos.com',
  'bangbros.com',
  'realitykings.com',
  'naughtyamerica.com',
  'digitalplayground.com',
  'teamskeet.com',
  'evilangel.com',
  'bang.com',
  'sex.com',
  'xhamsterlive.com',
  'flirt4free.com',
  'streamate.com',
  'imlive.com',
  'jerkmate.com',
  'adultfriendfinder.com',
  'friendfinder.com',
  'fetlife.com',
  'ashleymadison.com',
  'adultwork.com',
  'faphouse.com',
  'sexvid.xxx',
  'thisvid.com',
  'hentaifox.com',
  'nhentai.net',
  'rule34.xxx',
  'gelbooru.com',
  'danbooru.donmai.us',
  'f95zone.to',
  'literotica.com',
  'x-art.com',
  'metart.com',
  'metartx.com',
  'nubiles.net',
  'babes.com',
  'twistys.com',
  'vixen.com',
  'tushy.com',
  'blacked.com',
  'deeper.com',
  'letsgobi.com',
  'kink.com',
  'brazzersnetwork.com',
  'mature.nl',
  'private.com',
  'dorcelclub.com',
  'hustler.com',
  'playboyplus.com',
  'penthouse.com',
  'clips4sale.com',
  'manyvids.com',
  'iwantclips.com',
  'avn.com',
  'adultdvdempire.com',
  'xhamster.desi',
  'gotporn.com',
  'porngo.com',
  'planetromeo.com',
  'gaytube.com',
  'boyfriendtv.com',
  'manhunt.net',
  'squirt.org',
  'xtube.com',
  'gaymaletube.com',
  'gayporn.fm',
  'homo.xxx',
  'javhd.com',
  'japorn.tv',
  'tokyomotion.net',
  'watchjavonline.com',
  'caribbeancom.com',
  '1pondo.tv',
  'heyzo.com',
  '10musume.com',
  'pacopacomama.com',
  'adulttime.com',
  'wicked.com',
  'bangbus.com',
  'publicagent.com',
  'fakehub.com',
  'hentaigasm.com',
  'xgroovy.com',
  'alohatube.com',
  'pornhat.com',
  'fapello.com',
  'simpcity.su',
  'coomer.su',
  'fansly.com',
  'onlyfans.com',
];
