project_id = "funrqbkfprdsgbnrcker"

[functions.moderate-image]
verify_jwt = false

[functions.check-blocked-site]
verify_jwt = false

[functions.accountability]
verify_jwt = false

[functions.proxy-reader]
verify_jwt = false

[functions.web-search]
verify_jwt = false
